### ISSUE TITLE
Criar o wireframe da tela inicial

### ISSUE THREAD

**Issue by alefemoreira** [alefemoreira/iBattery#2]
Siga os seguintes requisitos

* Contraste
* Alinhamento
* Combinação de cores
* Equilíbrio de elementos

Items

* Switch button for on/off alarm
* Show state of cellphone pluged

**Comment by alefemoreira** [comment]
Color Pallete Light

```CSS
/* Color Theme Swatches in Hex */
.iBattery-1-hex { color: #B30000; }
.iBattery-2-hex { color: #FF1919; }
.iBattery-3-hex { color: #FF0000; }
.iBattery-4-hex { color: #00B333; }
.iBattery-5-hex { color: #00FF48; }

/* Color Theme Swatches in RGBA */
.iBattery-1-rgba { color: rgba(179, 0, 0, 1); }
.iBattery-2-rgba { color: rgba(255, 25, 25, 1); }
.iBattery-3-rgba { color: rgba(255, 0, 0, 1); }
.iBattery-4-rgba { color: rgba(0, 179, 51, 1); }
.iBattery-5-rgba { color: rgba(0, 255, 72, 1); }

/* Color Theme Swatches in HSLA */
.iBattery-1-hsla { color: hsla(0, 100, 35, 1); }
.iBattery-2-hsla { color: hsla(0, 100, 54, 1); }
.iBattery-3-hsla { color: hsla(0, 100, 50, 1); }
.iBattery-4-hsla { color: hsla(137, 100, 35, 1); }
.iBattery-5-hsla { color: hsla(136, 100, 50, 1); }
```

Color Pallete Darker

```CSS
/* Color Theme Swatches in Hex */
.iBatteryDark-1-hex { color: #B31212; }
.iBatteryDark-2-hex { color: #FF4D4D; }
.iBatteryDark-3-hex { color: #FF3333; }
.iBatteryDark-4-hex { color: #00B333; }
.iBatteryDark-5-hex { color: #33FF6D; }

/* Color Theme Swatches in RGBA */
.iBatteryDark-1-rgba { color: rgba(179, 18, 18, 1); }
.iBatteryDark-2-rgba { color: rgba(255, 77, 77, 1); }
.iBatteryDark-3-rgba { color: rgba(255, 51, 51, 1); }
.iBatteryDark-4-rgba { color: rgba(0, 179, 51, 1); }
.iBatteryDark-5-rgba { color: rgba(51, 255, 109, 1); }

/* Color Theme Swatches in HSLA */
.iBatteryDark-1-hsla { color: hsla(0, 81, 38, 1); }
.iBatteryDark-2-hsla { color: hsla(0, 100, 65, 1); }
.iBatteryDark-3-hsla { color: hsla(0, 100, 60, 1); }
.iBatteryDark-4-hsla { color: hsla(137, 100, 35, 1); }
.iBatteryDark-5-hsla { color: hsla(137, 100, 60, 1); }
```
